/* Generated By:JJTree: Do not edit this line. ASTDebugEx.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTDebugEx extends SimpleNode {
  public ASTDebugEx(int id) {
    super(id);
  }

  public ASTDebugEx(parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d5d2cac96a3dd7d8d0d82ebbae4859d3 (do not edit this line) */
