/* Generated By:JJTree: Do not edit this line. ASTdomain1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTdomain1 extends SimpleNode {
  public ASTdomain1(int id) {
    super(id);
  }

  public ASTdomain1(parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=17e3fdca7202ef81db4545fc573d7d38 (do not edit this line) */
