/* Generated By:JJTree: Do not edit this line. ASTDebugEx1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTDebugEx1 extends SimpleNode {
  public ASTDebugEx1(int id) {
    super(id);
  }

  public ASTDebugEx1(parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(parserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b5debccdae5054e4dc4c18614d9cd7a (do not edit this line) */
