/* Generated By:JJTree: Do not edit this line. ASTN_PolimorPara.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTN_PolimorPara extends SimpleNode {
  public ASTN_PolimorPara(int id) {
    super(id);
  }

  public ASTN_PolimorPara(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f953d675fe1b35487f822d5f1de999e1 (do not edit this line) */
