/* Generated By:JJTree: Do not edit this line. ASTN_ParaList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTN_ParaList extends SimpleNode {
  public ASTN_ParaList(int id) {
    super(id);
  }

  public ASTN_ParaList(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=233df4510b6bd8ae0323ec6b9d2ebc5d (do not edit this line) */
