/* Generated By:JJTree: Do not edit this line. ASTN_Domain.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTN_Domain extends SimpleNode {
  public ASTN_Domain(int id) {
    super(id);
  }

  public ASTN_Domain(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6e80d7ae7b94397cad05d9e9b900c472 (do not edit this line) */
