/* Generated By:JJTree: Do not edit this line. ASTN_PolymorPara.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTN_PolymorPara extends SimpleNode {
  public ASTN_PolymorPara(int id) {
    super(id);
  }

  public ASTN_PolymorPara(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=405db45a5d373bcb3c6301edab390301 (do not edit this line) */
