/* Generated By:JJTree: Do not edit this line. ASTN_PluginExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTN_PluginExp extends SimpleNode {
  public ASTN_PluginExp(int id) {
    super(id);
  }

  public ASTN_PluginExp(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2fc9cbf17a5befcc75405f00dcf32570 (do not edit this line) */
