/* Generated By:JJTree: Do not edit this line. ASTPluginEx1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTPluginEx1 extends SimpleNode {
  public ASTPluginEx1(int id) {
    super(id);
  }

  public ASTPluginEx1(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3fd60c7ffc0af318ef69ff9694f18e3 (do not edit this line) */
