/* Generated By:JJTree: Do not edit this line. ASTPolymorPara.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTPolymorPara extends SimpleNode {
  public ASTPolymorPara(int id) {
    super(id);
  }

  public ASTPolymorPara(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=90f19151f95eb5a8c792ec026de92d59 (do not edit this line) */
