/* Generated By:JJTree: Do not edit this line. ASTPolimolPara.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.parse.SOP;

public
class ASTPolimolPara extends SimpleNode {
  public ASTPolimolPara(int id) {
    super(id);
  }

  public ASTPolimolPara(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a86237d713d50f31175a6c4acab9ab4e (do not edit this line) */
