/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package logic.parse.SOP;

public interface ParserTreeConstants
{
  public int JJTRECIPIENT = 0;
  public int JJTPLUGINEX = 1;
  public int JJTPLUGIN = 2;
  public int JJTADDRESS = 3;
  public int JJTDOMAIN = 4;
  public int JJTVOID = 5;
  public int JJTEXCEPTION = 6;
  public int JJTUNION = 7;
  public int JJTINTERSECTION = 8;
  public int JJTEXP = 9;
  public int JJTPARALIS = 10;
  public int JJTPOLIMOLPARA = 11;
  public int JJTRULE = 12;
  public int JJTVALUE = 13;
  public int JJTSUBDOMAIN = 14;
  public int JJTARG = 15;
  public int JJTFUNCTION = 16;
  public int JJTALIAS = 17;
  public int JJTCOMMAND = 18;
  public int JJTCOMMANDARG = 19;
  public int JJTDOMAINARG = 20;
  public int JJTRECIPIENT1 = 21;
  public int JJTPLUGINEX1 = 22;
  public int JJTADDRESS1 = 23;
  public int JJTPARAS1 = 24;
  public int JJTDOMAIN1 = 25;


  public String[] jjtNodeName = {
    "Recipient",
    "PluginEx",
    "Plugin",
    "Address",
    "domain",
    "void",
    "Exception",
    "Union",
    "Intersection",
    "Exp",
    "Paralis",
    "PolimolPara",
    "Rule",
    "Value",
    "Subdomain",
    "Arg",
    "function",
    "alias",
    "command",
    "commandArg",
    "DomainArg",
    "Recipient1",
    "PluginEx1",
    "Address1",
    "Paras1",
    "domain1",
  };
}
/* JavaCC - OriginalChecksum=1866434470da18b91e8fdde858f53029 (do not edit this line) */
