/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package logic.parse.SOP;

public interface ParserTreeConstants
{
  public int JJTRECIPIENT = 0;
  public int JJTPLUGINEXP = 1;
  public int JJTPLUGIN = 2;
  public int JJTADDRESS = 3;
  public int JJTDOMAIN = 4;
  public int JJTVOID = 5;
  public int JJTEXCEPTION = 6;
  public int JJTUNION = 7;
  public int JJTINTERSECTION = 8;
  public int JJTEXP = 9;
  public int JJTPARALIST = 10;
  public int JJTPOLIMORPARA = 11;
  public int JJTFUNCTION = 12;
  public int JJTCOMMAND = 13;
  public int JJTCOMMANDARG = 14;
  public int JJTDOMAINARG = 15;
  public int JJTRULE = 16;
  public int JJTVALUE = 17;
  public int JJTN_RECIPIENT = 18;
  public int JJTN_PLUGINEXP = 19;
  public int JJTN_ADDRESS = 20;
  public int JJTN_PARAS = 21;
  public int JJTN_PARALIST = 22;
  public int JJTN_POLIMORPARA = 23;


  public String[] jjtNodeName = {
    "Recipient",
    "PluginExp",
    "Plugin",
    "Address",
    "Domain",
    "void",
    "Exception",
    "Union",
    "Intersection",
    "Exp",
    "ParaList",
    "PolimorPara",
    "function",
    "command",
    "commandArg",
    "domainArg",
    "rule",
    "value",
    "N_Recipient",
    "N_PluginExp",
    "N_Address",
    "N_Paras",
    "N_ParaList",
    "N_PolimorPara",
  };
}
/* JavaCC - OriginalChecksum=0aca809bfab128aa451fb621fcf0a810 (do not edit this line) */
