/* Generated By:JJTree&JavaCC: Do not edit this line. parserConstants.java */
package logic.parse.SOP;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int PERIOD = 7;
  /** RegularExpression Id. */
  int VIRTICAL = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int OP_BRACE = 10;
  /** RegularExpression Id. */
  int END_BRACE = 11;
  /** RegularExpression Id. */
  int AT = 12;
  /** RegularExpression Id. */
  int HASH = 13;
  /** RegularExpression Id. */
  int ARG = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"-\"",
    "\"+\"",
    "\".\"",
    "\"|\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"#\"",
    "<ARG>",
  };

}
