/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package logic.parse.SOP;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRecipient node, Object data);
  public Object visit(ASTPluginExp node, Object data);
  public Object visit(ASTPlugin node, Object data);
  public Object visit(ASTCommandTarget node, Object data);
  public Object visit(ASTCommandExp node, Object data);
  public Object visit(ASTCommandPara node, Object data);
  public Object visit(ASTAddress node, Object data);
  public Object visit(ASTDomain node, Object data);
  public Object visit(ASTException node, Object data);
  public Object visit(ASTUnion node, Object data);
  public Object visit(ASTIntersection node, Object data);
  public Object visit(ASTExp node, Object data);
  public Object visit(ASTParaList node, Object data);
  public Object visit(ASTPolymorPara node, Object data);
  public Object visit(ASTfunction node, Object data);
  public Object visit(ASTcommand node, Object data);
  public Object visit(ASTcommandArg node, Object data);
  public Object visit(ASTdomainArg node, Object data);
  public Object visit(ASTrule node, Object data);
  public Object visit(ASTvalue node, Object data);
  public Object visit(ASTN_Recipient node, Object data);
  public Object visit(ASTN_PluginExp node, Object data);
  public Object visit(ASTN_Address node, Object data);
  public Object visit(ASTN_Domain node, Object data);
  public Object visit(ASTN_Paras node, Object data);
  public Object visit(ASTN_ParaList node, Object data);
  public Object visit(ASTN_PolymorPara node, Object data);
}
/* JavaCC - OriginalChecksum=f758037bda6aa17c42633aec6e85966d (do not edit this line) */
