/* Generated By:JavaCC: Do not edit this line. parserVisitor.java Version 5.0 */
package logic.parse.SOP;

public interface parserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRecipient node, Object data);
  public Object visit(ASTDebugEx node, Object data);
  public Object visit(ASTDebug node, Object data);
  public Object visit(ASTAddress node, Object data);
  public Object visit(ASTdomain node, Object data);
  public Object visit(ASTException node, Object data);
  public Object visit(ASTUnion node, Object data);
  public Object visit(ASTIntersection node, Object data);
  public Object visit(ASTExp node, Object data);
  public Object visit(ASTParalis node, Object data);
  public Object visit(ASTPolimolPara node, Object data);
  public Object visit(ASTRule node, Object data);
  public Object visit(ASTValue node, Object data);
  public Object visit(ASTSubdomain node, Object data);
  public Object visit(ASTArg node, Object data);
  public Object visit(ASTfunction node, Object data);
  public Object visit(ASTalias node, Object data);
  public Object visit(ASTcommand node, Object data);
  public Object visit(ASTcommandArg node, Object data);
  public Object visit(ASTDomainArg node, Object data);
  public Object visit(ASTRecipient1 node, Object data);
  public Object visit(ASTDebugEx1 node, Object data);
  public Object visit(ASTAddress1 node, Object data);
  public Object visit(ASTParas1 node, Object data);
  public Object visit(ASTdomain1 node, Object data);
}
/* JavaCC - OriginalChecksum=3004882775abae203085df596b1856c6 (do not edit this line) */
