/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package logic.parse.SOP;

public interface ParserTreeConstants
{
  public int JJTRECIPIENT = 0;
  public int JJTPLUGINEXP = 1;
  public int JJTPLUGIN = 2;
  public int JJTCOMMANDTARGET = 3;
  public int JJTVOID = 4;
  public int JJTCOMMANDEXP = 5;
  public int JJTCOMMANDPARA = 6;
  public int JJTADDRESS = 7;
  public int JJTDOMAIN = 8;
  public int JJTEXCEPTION = 9;
  public int JJTUNION = 10;
  public int JJTINTERSECTION = 11;
  public int JJTEXP = 12;
  public int JJTPARALIST = 13;
  public int JJTPOLYMORPARA = 14;
  public int JJTFUNCTION = 15;
  public int JJTCOMMAND = 16;
  public int JJTCOMMANDARG = 17;
  public int JJTDOMAINARG = 18;
  public int JJTRULE = 19;
  public int JJTVALUE = 20;
  public int JJTN_RECIPIENT = 21;
  public int JJTN_PLUGINEXP = 22;
  public int JJTN_ADDRESS = 23;
  public int JJTN_DOMAIN = 24;
  public int JJTN_PARAS = 25;
  public int JJTN_PARALIST = 26;
  public int JJTN_POLYMORPARA = 27;


  public String[] jjtNodeName = {
    "Recipient",
    "PluginExp",
    "Plugin",
    "CommandTarget",
    "void",
    "CommandExp",
    "CommandPara",
    "Address",
    "Domain",
    "Exception",
    "Union",
    "Intersection",
    "Exp",
    "ParaList",
    "PolymorPara",
    "function",
    "command",
    "commandArg",
    "domainArg",
    "rule",
    "value",
    "N_Recipient",
    "N_PluginExp",
    "N_Address",
    "N_Domain",
    "N_Paras",
    "N_ParaList",
    "N_PolymorPara",
  };
}
/* JavaCC - OriginalChecksum=6a415fcc96c253e6f4e71bea842c80c8 (do not edit this line) */
